language: python
python:
  - "2.7"
before_install:
  - "sudo apt-get -qq update"
install:
  - "sudo apt-get -qq install libxml2-dev libxslt-dev python-dev"
  - "pip install -r requirements.txt"
script: "./makexpi.sh"
